// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALy79K4lC9RJOPZ5b_z0FYOVsHkoX2bcw',
    appId: '1:96826120955:web:616f558157a96764edae5e',
    messagingSenderId: '96826120955',
    projectId: 'flat-data-cli',
    authDomain: 'flat-data-cli.firebaseapp.com',
    storageBucket: 'flat-data-cli.appspot.com',
    measurementId: 'G-K3ZHHM76WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdifiLt_CB4wQPvrYddLrmSiHqwGpKFY',
    appId: '1:96826120955:android:63bc02480a186c90edae5e',
    messagingSenderId: '96826120955',
    projectId: 'flat-data-cli',
    storageBucket: 'flat-data-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2-bICbRrqX8tC1iHtzQWA2RcyrAWHZpM',
    appId: '1:96826120955:ios:93f8e914165ce574edae5e',
    messagingSenderId: '96826120955',
    projectId: 'flat-data-cli',
    storageBucket: 'flat-data-cli.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2-bICbRrqX8tC1iHtzQWA2RcyrAWHZpM',
    appId: '1:96826120955:ios:93f8e914165ce574edae5e',
    messagingSenderId: '96826120955',
    projectId: 'flat-data-cli',
    storageBucket: 'flat-data-cli.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALy79K4lC9RJOPZ5b_z0FYOVsHkoX2bcw',
    appId: '1:96826120955:web:d5b4719dce64244aedae5e',
    messagingSenderId: '96826120955',
    projectId: 'flat-data-cli',
    authDomain: 'flat-data-cli.firebaseapp.com',
    storageBucket: 'flat-data-cli.appspot.com',
    measurementId: 'G-NLJ7Y5CYQJ',
  );
}
